apiVersion: v1
kind: Service
metadata:
  name: active-mq
  namespace: pulsar
  labels:
    app: active-mq
spec:
  selector:
    app: active-mq
  ports:
    - name: dashboard
      port: 8161
      targetPort: 8161
      protocol: TCP
    - name: openwire
      port: 61616
      targetPort: 61616
      protocol: TCP
    - name: amqp
      port: 5672
      targetPort: 5672
      protocol: TCP
    - name: stomp
      port: 61613
      targetPort: 61613
      protocol: TCP
    - name: mqtt
      port: 1883
      targetPort: 1883
      protocol: TCP
  type: ClusterIP